<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>ZeOverlay.Stage.Recognition</RootNamespace>
    <AssemblyName>ZeOverlay.Stage.Recognition</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZeOverlay.Shared\ZeOverlay.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ZeOverlay.Tests" />
  </ItemGroup>
</Project>
