<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>ZeOverlay</Product>
    <Company>ZeOverlay</Company>
    <Version>0.1.0</Version>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
