<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ZeOverlay.Stage.Matching</RootNamespace>
    <AssemblyName>ZeOverlay.Stage.Matching</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeOverlay.Shared\ZeOverlay.Shared.csproj" />
  </ItemGroup>

</Project>

